# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 826)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 106, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 106, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 106, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 56, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 40, 1011, 631))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.stackedWidget.setPalette(palette)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 931, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 213, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 191, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayoutWidget = QtWidgets.QWidget(self.page)
        self.formLayoutWidget.setGeometry(QtCore.QRect(360, 100, 291, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox_MOS = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_MOS.setMinimum(1)
        self.spinBox_MOS.setMaximum(5)
        self.spinBox_MOS.setObjectName("spinBox_MOS")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_MOS)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_CODEC = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_CODEC.setObjectName("label_CODEC")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_CODEC)
        self.gridLayoutWidget = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 160, 337, 169))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.spinBox_Nl = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_Nl.setMaximum(999)
        self.spinBox_Nl.setObjectName("spinBox_Nl")
        self.gridLayout.addWidget(self.spinBox_Nl, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.spinBox_Pll = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.spinBox_Pll.setMaximum(100.0)
        self.spinBox_Pll.setSingleStep(0.01)
        self.spinBox_Pll.setObjectName("spinBox_Pll")
        self.gridLayout.addWidget(self.spinBox_Pll, 3, 1, 1, 1)
        self.spinBox_Nc = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_Nc.setMaximum(999)
        self.spinBox_Nc.setObjectName("spinBox_Nc")
        self.gridLayout.addWidget(self.spinBox_Nc, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.SpinBox_Tpll = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.SpinBox_Tpll.setMaximum(999.99)
        self.SpinBox_Tpll.setSingleStep(0.01)
        self.SpinBox_Tpll.setObjectName("SpinBox_Tpll")
        self.gridLayout.addWidget(self.SpinBox_Tpll, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(550, 160, 342, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox_BWres = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spinBox_BWres.setMaximum(9999.0)
        self.spinBox_BWres.setSingleStep(0.01)
        self.spinBox_BWres.setObjectName("spinBox_BWres")
        self.gridLayout_2.addWidget(self.spinBox_BWres, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.spinBox_Rt = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spinBox_Rt.setMaximum(999.99)
        self.spinBox_Rt.setSingleStep(0.01)
        self.spinBox_Rt.setObjectName("spinBox_Rt")
        self.gridLayout_2.addWidget(self.spinBox_Rt, 1, 1, 1, 1)
        self.spinBox_Rr = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spinBox_Rr.setMaximum(999.99)
        self.spinBox_Rr.setSingleStep(0.01)
        self.spinBox_Rr.setObjectName("spinBox_Rr")
        self.gridLayout_2.addWidget(self.spinBox_Rr, 2, 1, 1, 1)
        self.spinBox_jitter = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.spinBox_jitter.setMaximum(999.99)
        self.spinBox_jitter.setSingleStep(0.01)
        self.spinBox_jitter.setObjectName("spinBox_jitter")
        self.gridLayout_2.addWidget(self.spinBox_jitter, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(230, 440, 581, 22))
        self.label_9.setObjectName("label_9")
        self.button_continuar1 = QtWidgets.QPushButton(self.page)
        self.button_continuar1.setGeometry(QtCore.QRect(800, 520, 155, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_continuar1.setPalette(palette)
        self.button_continuar1.setObjectName("button_continuar1")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(60, 20, 931, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_14.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(390, 80, 251, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.label_VPS = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_VPS.setObjectName("label_VPS")
        self.horizontalLayout_3.addWidget(self.label_VPS)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(130, 140, 807, 281))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_RetardoConjunto1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoConjunto1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoConjunto1.setObjectName("label_RetardoConjunto1")
        self.gridLayout_3.addWidget(self.label_RetardoConjunto1, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 0, 1, 1)
        self.label_RetardoRed1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoRed1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoRed1.setObjectName("label_RetardoRed1")
        self.gridLayout_3.addWidget(self.label_RetardoRed1, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 5, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_RetardoConjunto2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoConjunto2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoConjunto2.setObjectName("label_RetardoConjunto2")
        self.gridLayout_3.addWidget(self.label_RetardoConjunto2, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_RetardoAntijitter1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoAntijitter1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoAntijitter1.setObjectName("label_RetardoAntijitter1")
        self.gridLayout_3.addWidget(self.label_RetardoAntijitter1, 4, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 6, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 7, 0, 1, 1)
        self.label_RetardoAlgoritmico1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoAlgoritmico1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoAlgoritmico1.setObjectName("label_RetardoAlgoritmico1")
        self.gridLayout_3.addWidget(self.label_RetardoAlgoritmico1, 2, 1, 1, 1)
        self.label_RetardoDecodificacion1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoDecodificacion1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoDecodificacion1.setObjectName("label_RetardoDecodificacion1")
        self.gridLayout_3.addWidget(self.label_RetardoDecodificacion1, 5, 1, 1, 1)
        self.label_RetardoTotal1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoTotal1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoTotal1.setObjectName("label_RetardoTotal1")
        self.gridLayout_3.addWidget(self.label_RetardoTotal1, 6, 1, 1, 1)
        self.label_NpaquetesRTP1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_NpaquetesRTP1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NpaquetesRTP1.setObjectName("label_NpaquetesRTP1")
        self.gridLayout_3.addWidget(self.label_NpaquetesRTP1, 7, 1, 1, 1)
        self.label_RetardoAlgoritmico2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoAlgoritmico2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoAlgoritmico2.setObjectName("label_RetardoAlgoritmico2")
        self.gridLayout_3.addWidget(self.label_RetardoAlgoritmico2, 2, 2, 1, 1)
        self.label_RetardoRed2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoRed2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoRed2.setObjectName("label_RetardoRed2")
        self.gridLayout_3.addWidget(self.label_RetardoRed2, 3, 2, 1, 1)
        self.label_RetardoAntijitter2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoAntijitter2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoAntijitter2.setObjectName("label_RetardoAntijitter2")
        self.gridLayout_3.addWidget(self.label_RetardoAntijitter2, 4, 2, 1, 1)
        self.label_RetardoDecodificacion1_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoDecodificacion1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoDecodificacion1_2.setObjectName("label_RetardoDecodificacion1_2")
        self.gridLayout_3.addWidget(self.label_RetardoDecodificacion1_2, 5, 2, 1, 1)
        self.label_RetardoTotal2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_RetardoTotal2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoTotal2.setObjectName("label_RetardoTotal2")
        self.gridLayout_3.addWidget(self.label_RetardoTotal2, 6, 2, 1, 1)
        self.label_NpaquetesRTP2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_NpaquetesRTP2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_NpaquetesRTP2.setObjectName("label_NpaquetesRTP2")
        self.gridLayout_3.addWidget(self.label_NpaquetesRTP2, 7, 2, 1, 1)
        self.button_calcularRt = QtWidgets.QPushButton(self.page_2)
        self.button_calcularRt.setGeometry(QtCore.QRect(130, 420, 199, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_calcularRt.setPalette(palette)
        self.button_calcularRt.setObjectName("button_calcularRt")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(120, 470, 811, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_BufferAntijitterElegido = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_BufferAntijitterElegido.setObjectName("label_BufferAntijitterElegido")
        self.gridLayout_4.addWidget(self.label_BufferAntijitterElegido, 1, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(480, 580, 481, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout.addWidget(self.label_45)
        self.label_RetardoTotalFinal = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_RetardoTotalFinal.setObjectName("label_RetardoTotalFinal")
        self.horizontalLayout.addWidget(self.label_RetardoTotalFinal)
        self.button_continuar2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_continuar2.setPalette(palette)
        self.button_continuar2.setObjectName("button_continuar2")
        self.horizontalLayout.addWidget(self.button_continuar2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_46 = QtWidgets.QLabel(self.page_3)
        self.label_46.setGeometry(QtCore.QRect(30, 20, 921, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_46.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(270, 80, 461, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_BHT = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_BHT.setPalette(palette)
        self.button_BHT.setObjectName("button_BHT")
        self.horizontalLayout_4.addWidget(self.button_BHT)
        self.label_BHT = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_BHT.setObjectName("label_BHT")
        self.horizontalLayout_4.addWidget(self.label_BHT)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.page_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(120, 160, 761, 181))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_BWll_cRTP = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_BWll_cRTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWll_cRTP.setObjectName("label_BWll_cRTP")
        self.gridLayout_5.addWidget(self.label_BWll_cRTP, 1, 2, 1, 1)
        self.button_BWSIPTRUNK = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_BWSIPTRUNK.setPalette(palette)
        self.button_BWSIPTRUNK.setObjectName("button_BWSIPTRUNK")
        self.gridLayout_5.addWidget(self.button_BWSIPTRUNK, 2, 0, 1, 1)
        self.label_BWSIPTRUNK_cRTP = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_BWSIPTRUNK_cRTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWSIPTRUNK_cRTP.setObjectName("label_BWSIPTRUNK_cRTP")
        self.gridLayout_5.addWidget(self.label_BWSIPTRUNK_cRTP, 2, 2, 1, 1)
        self.button_BWll = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_BWll.setPalette(palette)
        self.button_BWll.setObjectName("button_BWll")
        self.gridLayout_5.addWidget(self.button_BWll, 1, 0, 1, 1)
        self.label_BWll_RTP = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_BWll_RTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWll_RTP.setObjectName("label_BWll_RTP")
        self.gridLayout_5.addWidget(self.label_BWll_RTP, 1, 1, 1, 1)
        self.label_BWSIPTRUNK_RTP = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_BWSIPTRUNK_RTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWSIPTRUNK_RTP.setWordWrap(True)
        self.label_BWSIPTRUNK_RTP.setObjectName("label_BWSIPTRUNK_RTP")
        self.gridLayout_5.addWidget(self.label_BWSIPTRUNK_RTP, 2, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 0, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 0, 2, 1, 1)
        self.button_informe = QtWidgets.QPushButton(self.page_3)
        self.button_informe.setGeometry(QtCore.QRect(580, 350, 141, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_informe.setPalette(palette)
        self.button_informe.setObjectName("button_informe")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.page_3)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(350, 510, 305, 80))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_CODEC = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.comboBox_CODEC.setPalette(palette)
        self.comboBox_CODEC.setObjectName("comboBox_CODEC")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_CODEC, 0, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 0, 0, 1, 1)
        self.button_cambiarParametros = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_cambiarParametros.setPalette(palette)
        self.button_cambiarParametros.setObjectName("button_cambiarParametros")
        self.gridLayout_6.addWidget(self.button_cambiarParametros, 1, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 1, 0, 1, 1)
        self.label_InformeGenerado = QtWidgets.QLabel(self.page_3)
        self.label_InformeGenerado.setGeometry(QtCore.QRect(390, 410, 232, 28))
        self.label_InformeGenerado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_InformeGenerado.setObjectName("label_InformeGenerado")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "PARÁMETROS DE ENTRADA"))
        self.label.setText(_translate("MainWindow", "MOS"))
        self.label_2.setText(_translate("MainWindow", "CODEC elegido:"))
        self.label_CODEC.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "Probabilidad llamada (Pll)"))
        self.label_7.setText(_translate("MainWindow", "Tiempo medio de llamada (Tpll)"))
        self.label_4.setText(_translate("MainWindow", "Número de empresas cliente (Nc)"))
        self.label_6.setText(_translate("MainWindow", "Número de líneas por cliente (Nl)"))
        self.label_21.setText(_translate("MainWindow", "minutos"))
        self.label_23.setText(_translate("MainWindow", "%"))
        self.label_10.setText(_translate("MainWindow", "Ancho de banda de reserva (BWres):"))
        self.label_11.setText(_translate("MainWindow", "Retardo total (Rt)"))
        self.label_12.setText(_translate("MainWindow", "Retardo de red (Rr)"))
        self.label_13.setText(_translate("MainWindow", "Jitter total (J)"))
        self.label_15.setText(_translate("MainWindow", "Mbps"))
        self.label_3.setText(_translate("MainWindow", "ms"))
        self.label_17.setText(_translate("MainWindow", "ms"))
        self.label_19.setText(_translate("MainWindow", "ms"))
        self.label_9.setText(_translate("MainWindow", "*VOIP4ALL se conectará con el proveedor SIPTRUNK mediante PPPOE y la encapsulación 802.1q"))
        self.button_continuar1.setText(_translate("MainWindow", "Continuar"))
        self.label_14.setText(_translate("MainWindow", "Cálculo del retardo total (Rt)"))
        self.label_16.setText(_translate("MainWindow", "El VPS del CODEC elegido es de:"))
        self.label_VPS.setText(_translate("MainWindow", "-"))
        self.label_RetardoConjunto1.setText(_translate("MainWindow", "-"))
        self.label_18.setText(_translate("MainWindow", "Retardo conjunto, CODEC+Paquetización:"))
        self.label_22.setText(_translate("MainWindow", "Retardo del Buffer antijitter"))
        self.label_RetardoRed1.setText(_translate("MainWindow", "-"))
        self.label_24.setText(_translate("MainWindow", "Retardo decodificación en el destino "))
        self.label_28.setText(_translate("MainWindow", "RETARDOS"))
        self.label_RetardoConjunto2.setText(_translate("MainWindow", "-"))
        self.label_30.setText(_translate("MainWindow", "Buffer antijitter x2"))
        self.label_29.setText(_translate("MainWindow", "Buffer antijitter x1.5"))
        self.label_20.setText(_translate("MainWindow", "Retardo de red "))
        self.label_RetardoAntijitter1.setText(_translate("MainWindow", "-"))
        self.label_39.setText(_translate("MainWindow", "Retardo algoritmico"))
        self.label_26.setText(_translate("MainWindow", "Retardo total (Rt):"))
        self.label_31.setText(_translate("MainWindow", "Número de paquetes RTP almacenados en el buffer"))
        self.label_RetardoAlgoritmico1.setText(_translate("MainWindow", "-"))
        self.label_RetardoDecodificacion1.setText(_translate("MainWindow", "-"))
        self.label_RetardoTotal1.setText(_translate("MainWindow", "-"))
        self.label_NpaquetesRTP1.setText(_translate("MainWindow", "-"))
        self.label_RetardoAlgoritmico2.setText(_translate("MainWindow", "-"))
        self.label_RetardoRed2.setText(_translate("MainWindow", "-"))
        self.label_RetardoAntijitter2.setText(_translate("MainWindow", "-"))
        self.label_RetardoDecodificacion1_2.setText(_translate("MainWindow", "-"))
        self.label_RetardoTotal2.setText(_translate("MainWindow", "-"))
        self.label_NpaquetesRTP2.setText(_translate("MainWindow", "-"))
        self.button_calcularRt.setText(_translate("MainWindow", "Calcular retardo total"))
        self.label_BufferAntijitterElegido.setText(_translate("MainWindow", "-"))
        self.label_43.setText(_translate("MainWindow", "veces el valor del jitter máximo para satisfacer la condición del máximo retardo total introducido"))
        self.label_42.setText(_translate("MainWindow", "El buffer antijitter elegido debe ser de: "))
        self.label_45.setText(_translate("MainWindow", "Retardo total: "))
        self.label_RetardoTotalFinal.setText(_translate("MainWindow", "-"))
        self.button_continuar2.setText(_translate("MainWindow", "Continuar"))
        self.label_46.setText(_translate("MainWindow", "Cálculo del ancho de banda SIPTRUNK"))
        self.button_BHT.setText(_translate("MainWindow", "Calcular tráfico de hora cargada (BHT)"))
        self.label_BHT.setText(_translate("MainWindow", "-"))
        self.label_BWll_cRTP.setText(_translate("MainWindow", "-"))
        self.button_BWSIPTRUNK.setText(_translate("MainWindow", "Calcular ancho de banda SIPTRUNK"))
        self.label_BWSIPTRUNK_cRTP.setText(_translate("MainWindow", "-"))
        self.button_BWll.setText(_translate("MainWindow", "Calcular ancho de banda de una llamada (BWll)"))
        self.label_BWll_RTP.setText(_translate("MainWindow", "-"))
        self.label_BWSIPTRUNK_RTP.setText(_translate("MainWindow", "-"))
        self.label_53.setText(_translate("MainWindow", "RTP"))
        self.label_54.setText(_translate("MainWindow", "cRTP"))
        self.button_informe.setText(_translate("MainWindow", "Generar informe"))
        self.comboBox_CODEC.setItemText(0, _translate("MainWindow", "G.711 (64 Kbps)"))
        self.comboBox_CODEC.setItemText(1, _translate("MainWindow", "G.729 (8 Kbps)"))
        self.comboBox_CODEC.setItemText(2, _translate("MainWindow", "G.723.1 (6.3 Kbps)"))
        self.comboBox_CODEC.setItemText(3, _translate("MainWindow", "G.723.1 (5.3 Kbps)"))
        self.comboBox_CODEC.setItemText(4, _translate("MainWindow", "G.726 (32 Kbps)"))
        self.comboBox_CODEC.setItemText(5, _translate("MainWindow", "G.726 (24 Kbps)"))
        self.comboBox_CODEC.setItemText(6, _translate("MainWindow", "G.728 (16 Kbps)"))
        self.comboBox_CODEC.setItemText(7, _translate("MainWindow", "G.722_64k (64 Kbps)"))
        self.comboBox_CODEC.setItemText(8, _translate("MainWindow", "ilbc_mode_20 (15.2 Kbps)"))
        self.comboBox_CODEC.setItemText(9, _translate("MainWindow", "ilbc_mode_30 (13.33 Kbps)"))
        self.label_55.setText(_translate("MainWindow", "Elegir otro CODEC"))
        self.button_cambiarParametros.setText(_translate("MainWindow", "Cambiar parámetros de entrada"))
        self.label_56.setText(_translate("MainWindow", "O bien:"))
        self.label_InformeGenerado.setText(_translate("MainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

